# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

In [2]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [8]:
v1=np.ones(100)
print(v1, len(v1))
v2=np.array([1])
print(v2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.] 100
[1]


Create a vector with values ranging from 10 to 49

In [10]:
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [15]:
v1=np.linspace(0,0.8,5)
print(v1, type(v1))
v2=np.arange(0,1,0.2)
print(v2, type(v2))


[0.  0.2 0.4 0.6 0.8] <class 'numpy.ndarray'>
[0.  0.2 0.4 0.6 0.8] <class 'numpy.ndarray'>


Convert a float array into an integer array in place

In [20]:
float_array=np.array([0.2,5.6,4.3])
int_array=float_array.astype(int)
print(int_array)

[0 5 4]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [27]:
boolean_array=np.array([True,True,False,True])

where_true=np.where(boolean_array)
print(where_true)

inv=np.invert(boolean_array)
print(inv, type(inv))

(array([0, 1, 3], dtype=int64),)
[False False  True False] <class 'numpy.ndarray'>


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [41]:
u=np.array([[1,2,3]]).T
v=np.array([[1,1,1]]).T

sol1=np.dot(v.T,u)
print('inner product :', sol1)
sol2=np.matmul(v.T,u)
print('inner product :',sol2)

sol3=np.dot(u,v.T)
print('outer product : \n',sol3)
sol4=np.matmul(u,v.T)
print('outer product : \n',sol4)

sol5=np.add(u,v.T)
print('outer sum matrix :\n',sol5)
sol6=np.add(u,v.T)
print('outer sum matrix :\n',sol6)



inner product : [[6]]
inner product : [[6]]
outer product : 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
outer product : 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
outer sum matrix :
 [[2 2 2]
 [3 3 3]
 [4 4 4]]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [85]:
M=[[0,1,2],[3,4,5],[6,7,8]]
print('element in the middle : ', M[1][1] )

#-----------------------

M1=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(M1, type(M1))
print('element in the middle : ', M1[1][1] )
M2=np.matrix([[0,1,2],[3,4,5],[6,7,8]])
print(M2, type(M2))
print('element in the middle : ', M2[1,1] )

#-----------------------

M1[[0,1]]=M1[[1,0]]
print('swap rows for array : \n', M1)
M2[[0,1]]=M2[[1,0]]
print('swap rows for matrix: \n', M2)

#-----------------------

M1=np.array([[0,1,2],[3,4,5],[6,7,8]])
M2=np.matrix([[0,1,2],[3,4,5],[6,7,8]])

M1_sub1=M1[np.ix_([1,2],[1,2])]
print('submatrix : \n', M1_sub1)
M1_sub2=M1[1:3,1:3]
print('submatrix : \n', M1_sub2)
M1_sub3=M1[[[1],[2]],[1,2]]
print('submatrix : \n', M1_sub3)

#-----------------------

M1_d1=np.diag(M1)
print('diagonal : \n', M1_d1)
M1_d2=np.array([M1[k,k] for k in range(len(M1))])
print('diagonal : \n', M1_d2)

#-----------------------

M_cube1=np.dot(M,np.dot(M,M))
print('M cube : \n', M_cube1)
M_cube2=np.linalg.matrix_power(M,3)
print('M cube : \n', M_cube2)

#-----------------------

M_vect1=np.matrix.flatten(M2)
print('M vect : \n', M_vect1)
M_vect1_F=np.matrix.flatten(M2,'F')
print('M vect F: \n', M_vect1_F)

M_vect2=M1.reshape((1,9))
print('M vect : \n', M_vect2)
M_vect2_F=(M1.T).reshape((1,9))
print('M vect F : \n', M_vect2_F)

#-----------------------

v=np.array([[1,2,3]]).T

product1=np.dot(M1,v)
print("product : \n",product1)


element in the middle :  4
[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
element in the middle :  4
[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.matrix'>
element in the middle :  4
swap rows for array : 
 [[3 4 5]
 [0 1 2]
 [6 7 8]]
swap rows for matrix: 
 [[3 4 5]
 [0 1 2]
 [6 7 8]]
submatrix : 
 [[4 5]
 [7 8]]
submatrix : 
 [[4 5]
 [7 8]]
submatrix : 
 [[4 5]
 [7 8]]
diagonal : 
 [0 4 8]
diagonal : 
 [0 4 8]
M cube : 
 [[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]
M cube : 
 [[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]
M vect : 
 [[0 1 2 3 4 5 6 7 8]]
M vect F: 
 [[0 3 6 1 4 7 2 5 8]]
M vect : 
 [[0 1 2 3 4 5 6 7 8]]
M vect F : 
 [[0 3 6 1 4 7 2 5 8]]
product : 
 [[ 8]
 [26]
 [44]]


Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [93]:
def is_symmetric(M):
    if np.all(M==np.transpose(M)):
        return True
    else:
        return('matrix non-symmetric')

In [96]:
print('M:',is_symmetric(M2))

N=np.matrix([[1,5,3],[5,2,6],[3,6,7]])
print('N:',is_symmetric(N))

M: matrix non-symmetric
N: True


## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column